### ISSUE TITLE
Pharmacy price comparisons api

### ISSUE THREAD

**Issue by JMo911** [JMo911/DiagNotes#16]
User Story
As a doctor, I should be able to recommend affordable medications to my patients so that they can get better as soon as possible.

Acceptable Criteria
- [x] The appointment.html page needs a search box where doctors can search a medicine name
- [x] User should be able to use this search multiple times. Search for one medicine, get results, search for a different medicine, get new results...
- [ ] Upon submitting that search, the page should render several medication brand options
- [ ] each brand option should list the price
- [ ] (BONUS) list additional relevant information about the brands

**Comment by Gilpatrickgreg** [comment]
waiting for api key

**Comment by Gilpatrickgreg** [comment]
no longer using this api
