### ISSUE TITLE
Wireframes

### ISSUE THREAD

**Issue by JMo911** [JMo911/DiagNotes#5]
User Story
As a user our app should be visually appealing and very intuitive so that doctors and nurses enjoy using out product and have more time to dedicate to focusing on their patients.

Acceptable Criteria
- [x] wireframe for the log in page with all necessary elements on the page
- [x] wireframe for the log in page with all necessary elements on the page
- [x] wireframe for the log in page with all necessary elements on the page

**Comment by JMo911** [comment]
Please add to our images folder, and the powerpoint. Then feel free to close this issue.

**Comment by Gilpatrickgreg** [comment]
Criteria met.
