### ISSUE TITLE
Medical App Design Best Practices

### ISSUE THREAD

**Issue by liz-guenthner** [JMo911/DiagNotes#8]
User Story
As a member of medical staff, I want to use a an app that is intuitive to follow with a clean, minimal design. https://steelkiwi.com/blog/how-to-design-medical-websites-and-apps/

Acceptable Criteria
- [x] Use relaxing color for background
- [x] Use warm color for "call to actions" in order to stand out
- [x] Use san serif font to maintain clean design
- [x] Limit content with large amounts of negative space for ease of navigation

**Comment by Gilpatrickgreg** [comment]
Criteria met
