### ISSUE TITLE
media/logo design

### ISSUE THREAD

**Issue by Gorani1** [JMo911/DiagNotes#9]
users story
who A a user
what I want to use a professional looking application logo
why that is easily identified from users and the logo should mirror its function which are speech and notes. 

- [x]  light colors combination 
- [x]  Images or the physical file. 
- [x] Professional appearance 
- [x] Designing it in different shapes and forms to meet logo usability and displays.

**Comment by JMo911** [comment]
Logo looks awesome, thank you!
